# Nome do nosso fluxo de automação
name: Deploy Functions to Firebase

# Define o gatilho: este fluxo roda toda vez que você faz 'git push'
on:
  push:
    branches:
      # Lembre-se de trocar para 'master' se for o nome da sua branch principal
      - main 

jobs:
  deploy_functions:
    name: Deploy Cloud Functions
    # O robô do GitHub rodará em um ambiente Linux (Ubuntu) limpo
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Baixa o seu código do GitHub
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Passo 2: Configura o Node.js para a versão 20 (a mesma do nosso backend)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Passo 3: Entra na pasta 'functions' e instala as dependências dela
      - name: Install Functions Dependencies
        run: npm --prefix ./functions install

      # Passo 4: Instala as ferramentas do Firebase e faz o deploy diretamente
      - name: Deploy to Firebase
        run: |
          npm install -g firebase-tools
          firebase deploy --only functions --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive